let cart=[];const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),money=n=>`₹${n}`;
const wa=msg=>`https://wa.me/${SITE.business.wa}?text=${encodeURIComponent(msg)}`;
function allItems(){let a=[];SITE.menu.forEach(s=>{(s.items||[]).forEach(x=>a.push({x,s}));(s.groups||[]).forEach(g=>g[1].forEach(x=>a.push({x,s}))) });return a}
function item(id){return allItems().find(o=>o.x[0]===id)?.x}
function add(id,size,price,name){let key=id+(size?'|'+size:'');let x=cart.find(a=>a.key===key);if(x)x.qty++;else cart.push({key,id,name,size,price,qty:1});update();toast(`${name}${size?' ('+size+')':''} added`)}
function render(){let cats=['All',...SITE.menu.map(s=>s.cat)];$('#filters').innerHTML=cats.map((c,i)=>`<button class="filter ${i?'':'active'}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.cat,$('#search').value)});draw()}
function draw(cat='All',q=''){q=q.toLowerCase();let html='';SITE.menu.forEach(s=>{if(cat!=='All'&&s.cat!==cat)return;let groups=s.groups||[['',s.items||[]]];groups=groups.map(g=>[g[0],g[1].filter(x=>!q||x[0].toLowerCase().includes(q)||(x[2]||'').toLowerCase().includes(q))]).filter(g=>g[1].length);if(!groups.length)return;html+=`<article class="cat"><div class="catHead"><span>${s.emoji}</span><div><h3>${esc(s.cat)}</h3><small>${esc(s.sizes||s.note||'')}</small></div></div>${groups.map(g=>`${g[0]?`<div class="group">${esc(g[0])}</div>`:''}<div class="dishes">${g[1].map(x=>dish(x,s)).join('')}</div>`).join('')}${s.extra?`<div class="extra">➕ ${esc(s.extra[0])}<b>₹${s.extra[1]}</b></div>`:''}</article>`});$('#menuList').innerHTML=html||`<div class="empty">🔎<h3>No dishes found</h3><p>Try another search or category.</p></div>`;document.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(b.dataset.id,'',+b.dataset.price,b.dataset.name));document.querySelectorAll('.size').forEach(b=>b.onclick=()=>add(b.dataset.id,b.dataset.size,+b.dataset.price,b.dataset.name))}
function dish(x,s){let id=x[0].toLowerCase().replace(/[^a-z0-9]+/g,'-');let full=s.full?.[x[0]];if(full)return `<div class="dish"><div><b>${esc(x[0])}</b><small>${esc(x[2]||'')}</small></div><div class="sizes"><button class="size" data-id="${id}" data-size="Half" data-price="${x[1]}" data-name="${esc(x[0])}">Half ₹${x[1]}</button><button class="size" data-id="${id}" data-size="Full" data-price="${full}" data-name="${esc(x[0])}">Full ₹${full}</button></div></div>`;return `<div class="dish"><div><b>${esc(x[0])}</b><small>${esc(x[2]||'')}</small></div><div class="addArea"><strong>₹${x[1]}</strong><button class="add" data-id="${id}" data-price="${x[1]}" data-name="${esc(x[0])}">Add ＋</button></div></div>`}
function update(){let n=cart.reduce((a,x)=>a+x.qty,0),t=cart.reduce((a,x)=>a+x.qty*x.price,0);$('#countTop').textContent=n;$('#countBar').textContent=n;$('#barTotal').textContent=money(t);$('#total').textContent=money(t);$('#cartBar').classList.toggle('show',n>0);$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartRow"><div><b>${esc(x.name)}</b><small>${x.size?esc(x.size)+' · ':''}${money(x.price)} each</small></div><div class="qty"><button onclick="qty('${x.key}',-1)">−</button><b>${x.qty}</b><button onclick="qty('${x.key}',1)">+</button></div></div>`).join(''):'<p class="empty">Your cart is empty.</p>'}
function qty(k,d){let x=cart.find(a=>a.key===k);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(a=>a.key!==k);update()}
function message(){let t=cart.reduce((a,x)=>a+x.qty*x.price,0);return `Hi ${SITE.business.name}! 👋\n\nI'd like to place an order:\n\n${cart.map((x,i)=>`${i+1}. ${x.name}${x.size?' ('+x.size+')':''} × ${x.qty} = ${money(x.qty*x.price)}`).join('\n')}\n\n*Estimated total: ${money(t)}*\n\nName:\nPreferred pickup time:\nPayment screenshot:\n\nThank you! ❤️`}
function toast(m){let e=$('#toast');e.textContent='✓ '+m;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1800)}
function gallery(){ $('#galleryList').innerHTML=SITE.gallery.map(x=>`<figure><img src="${x[1]}" alt="${esc(x[0])}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="placeholder">${x[2]}</div><figcaption>${esc(x[0])}</figcaption></figure>`).join('') }
function reviews(){ $('#reviewsList').innerHTML=SITE.testimonials.map(x=>`<article><div class="stars">★★★★★</div><p>“${esc(x[1])}”</p><b>— ${esc(x[0])}</b></article>`).join('') }
function setupDelivery(){let d=SITE.business.delivery||{};if(!d.enabled){$('#delivery').style.display='none';return}$('#deliveryTitle').textContent=d.title||'Need delivery?';$('#deliveryText').textContent=d.text||'';$('#deliveryNote').textContent=d.note||'';$('#porterLink').href=d.porterUrl||'https://porter.in/';$('#uberLink').href=d.uberUrl||'https://www.uber.com/in/en/'}
function setupVacation(){let v=SITE.business.vacation||{};if(!v.enabled)return;$('#vacationTitle').textContent=v.title||'Kitchen Closed ❤️';$('#vacationMessage').textContent=v.message||'';$('#vacationReopen').textContent=v.reopenText||'';if(v.from||v.to){$('#vacationDates').textContent='📅 '+[v.from,v.to].filter(Boolean).join(' → ');$('#vacationDates').style.display='block'}$('#vacationOverlay').classList.add('open');document.body.classList.add('noScroll')}
function closeVacation(){ $('#vacationOverlay').classList.remove('open');document.body.classList.remove('noScroll')}
document.addEventListener('DOMContentLoaded',()=>{document.title=SITE.business.name+' | '+SITE.business.tagline;['headWA','heroWA','bottomWA','floatWA'].forEach(id=>$('#'+id).href=wa(`Hi ${SITE.business.name}! 👋 I'd like to place an order.`));setupDelivery();setupVacation();render();gallery();reviews();update();$('#search').oninput=e=>draw(document.querySelector('.filter.active')?.dataset.cat||'All',e.target.value);$('#hamb').onclick=()=>$('#nav').classList.toggle('open');$('#openCart').onclick=()=>$('#modal').classList.add('open');$('#barCart').onclick=()=>$('#modal').classList.add('open');$('#close').onclick=()=>$('#modal').classList.remove('open');$('#clear').onclick=()=>{cart=[];update()};$('#vacationClose').onclick=closeVacation;$('#vacationOkay').onclick=closeVacation;$('#vacationOverlay').onclick=e=>{if(e.target.id==='vacationOverlay')closeVacation()};$('#checkout').onclick=()=>{if(cart.length)window.open(wa(message()),'_blank')};});
