/* EDIT THIS FILE to change menu, prices, photos, testimonials or business details. */
const SITE={
 business:{name:'Ishi Cooks',phone:'+91 8077624506',wa:'918077624506',maps:'https://maps.app.goo.gl/RLzxXc73Stq51dRu6',location:'Gurugram, Haryana',tagline:'Homemade with Love ❤️',delivery:{enabled:true,title:'Need delivery?',text:'We currently focus on pickup. For delivery, you can book a Porter or Uber Parcel from your side.',porterUrl:'https://porter.in/',uberUrl:'https://www.uber.com/in/en/',note:'Please confirm the delivery availability and fare with the rider before booking.'},vacation:{enabled:false,title:'Kitchen Closed ❤️',message:'Ishi Cooks is taking a short break. We will be back soon!',from:'25-09-2026',to:'10-10-2026',reopenText:'We’ll be back soon. Thank you for understanding! ❤️'}},
 menu:[
  {cat:'Poha / Stuffed Parathas',emoji:'🌻',note:'All parathas prepared in desi ghee and served with Dahi & Amul Butter.',items:[
   ['Poha',70],['Desi Ghee Aloo Paratha',90],['Desi Ghee Aloo Pyaj Paratha',100],['Desi Ghee Paneer Pyaj Paratha',130],['Desi Ghee Paneer Paratha',140],['Cheesy Corn & Aloo Paratha',140]]},
  {cat:'Vermicelli / Macaroni / Pasta Bowls',emoji:'🍝',note:'Suji Based — No Maida',items:[['Veg Vermicelli Bowl',140],['Mac & Cheese Bowl',180],['Pink Sauce Pasta Bowl',180],['Masala Macaroni / Pasta Bowl',160]]},
  {cat:'Beverages',emoji:'🥤',groups:[['HOT',[['Tea',20],['Masala Tea',25,'Adrak, Elaichi, Tulsi, etc.'],['Coffee',40],['Bread Butter Toast',30,'2 pc']]],['COLD',[['Cold Coffee',80],['Sweet Lassi',80],['Banana Shake',70]]]]},
  {cat:'Maggi',emoji:'🍜',items:[['Plain Butter Maggi',40,'','Half'],['Veg Butter Maggi',60,'','Half']],full:{'Plain Butter Maggi':80,'Veg Butter Maggi':120},note:'Half / Full'},
  {cat:'Grilled Sandwiches',emoji:'🥪',items:[['Tandoori Veggie Grilled Sandwich',100],['Tandoori Paneer Grilled Sandwich',120]],extra:['Extra Amul Cheese Slice',15]},
  {cat:'Meal',emoji:'🍛',sizes:'Half = 250 ml • Full = 500 ml',items:[['Jeera Aloo',70,'Desi Ghee'],['Masala Aloo',70,'Desi Ghee fry'],['Aloo Tamatar Matar',70],['Yellow / Mix Dal',70],['Rajma / Chhole / Dal Makhani',70],['Paneer',110,'Kadhai / Butter / Matar'],['Paneer Bhurji',110],['Boondi Raita',50]],full:{'Jeera Aloo':140,'Masala Aloo':140,'Aloo Tamatar Matar':140,'Yellow / Mix Dal':140,'Rajma / Chhole / Dal Makhani':140,'Paneer':220,'Paneer Bhurji':220,'Boondi Raita':100},simple:[['Roti',15,'Desi Ghee'],['Paratha',20,'Desi Ghee']]},
  {cat:'Rice Bowls',emoji:'🍚',sizes:'Half Rice = 150 g • Full Rice = 300 g',items:[['Rajma / Chhole / Dal Makhani Rice Bowl',140],['Yellow / Mix Dal Rice Bowl',140],['Aloo Matar Rice Bowl',140],['Veg Pulao Bowl',140],['Moong Dal Veg Khichdi',140]]}
 ],
 gallery:[['Bowls','assets/gallery/bulk.jpg','🍛'],['Mac & Chesse and Masala Macroni','assets/gallery/mac_mac.jpg','🍝'],['Cold Coffee','assets/gallery/cold_coffee.jpg','🥤'],['Vermicelli With Hot Coffee','assets/gallery/vermicelli_coffee.jpg','🍱'],['Stuffed Paratha','assets/gallery/stuffed_paratha.jpg','❤️'],['Poori Sabji','assets/gallery/poori_sabji.jpg','🫓']],
 testimonials:[['Utkarsh Gautam','Hi Sparsh and Shikha I just wanted to thank you for the meals. I have shifted out of my PG today as I have been staffed to Bangalore so I won\'t be able to order anymore. But I want to say that the food that you guys are providing is fantastic. It\'s healthy and homely and the portion sizes are fantastic. Also I have loved the small touches too like giving a choco-mini with the meal and customising the spices in the dishes. Moreover the portion sizes are so good that it makes every order economical. I have to say that you guys served me the best pink pasta I have ever had.  The rajma rice bowl and the mac and cheese bowl took me back home. Will be recommending you to my friends for sure Keep up the good work, onwards and upwards!'],['Vishal','Just wanted to say that I\'ve ordered from you twice now and I genuinely loved the food both times. The quality, taste and especially the quantity are really amazing.❤️ It\'s honestly great to have such good home-cooked food nearby. Please keep going with this, you\'re doing a really great job!🙌 Wishing you s of success. And if there\'s ever any way I can support or help you out, I\'d be happy to.😊'],['Uditaa','Hi Sparsh and Shikha. My boyfriend had previously ordered an aloo paratha, a paneer paratha and tea from you. I’ve been really sick since the last 2 days and honestly your food made me feel so much better. We\'ve both just recently shifted to Gurgaon. I\'m from Andamans and he\'s from Bhubaneswar, which is also my college city where we both met. And although we have a subscribed tiffin service, the meals we order from you have been the best part of our day. A friend of mine will also be shifting in tomorrow and the first thing I\'m going to get him is a full size Mac & Cheese pasta bowl from you (we both are quite big pasta connoisseurs) Thanks again for the amazing food. Will keep ordering from you. :)Add another genuine customer experience here.']]
};
